INCLUDE(${CMAKE_CURRENT_LIST_DIR}/x86_64.cmake)

SET(CMAKE_SYSTEM_PROCESSOR armv7a)
SET(TARGET armv7a-linux-androideabi)
SET(API 23)

SET(CMAKE_C_COMPILER ${COMPILER_ROOT}/${TARGET}${API}-clang)
SET(CMAKE_CXX_COMPILER ${COMPILER_ROOT}/${TARGET}${API}-clang++)
SET(CMAKE_LINKER ${COMPILER_ROOT}/ld)
SET(CMAKE_NM ${COMPILER_ROOT}/llvm-nm)
SET(CMAKE_OBJCOPY ${COMPILER_ROOT}/llvm-objcopy)
SET(CMAKE_OBJDUMP ${COMPILER_ROOT}/llvm-objdump)
SET(CMAKE_RANLIB ${COMPILER_ROOT}/llvm-ranlib)
